events {
    worker_connections 1024;
}

http {
    server {
        # O Nginx escuta na porta 80 (padrão web)
        listen 80;

        location / {
            # Comunicação interna: O Nginx usa o nome do serviço "api" para achar o FastAPI
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}